spring:
  application:
    name: WorkHub Api Gateway
server:
  port: 8085

UserService: http://localhost:8081
cookie:
  expireTime: 3600
env: dev
TaskService: http://localhost:8082
WorkHub_UI: http://localhost:3000

logging:
  level:
    com.manish.WorkHub.client.UserClient: DEBUG

secret:
  key: CHEFsEVfypW#7g9^k*Z8$VTaK+HaV^uv